SERVICE_USER_DEV:
  USER: EPOS_ETL_DEV_USER
  USER_SECRET_KEY: EPOS_ETL_DEV_USER
  ETL_ROLE: RL_DEV_KIWI_ETL
  FEATURE_ENV_ETL_ROLE: RL_DEV_KIWI_MANAGE_TEST_DB
  WHS: WHS_DEV_KIWI_ETL_X2LARGE
  ROUTE: LOCAL

ENGINEER_DEV:
  ETL_ROLE: RL_DEV_KIWI_ENGINEER
  WHS: WHS_DEV_KIWI_ETL_X2LARGE
  ROUTE: AWS

MIGRATIONS_DIR: migrations/
ROLLBACKS_DIR: rollbacks/
DDL_DIR: SqlDBM/src/

GITHUB_SERVICE_USER_SSM_SECRET_NAME: KIWI_GITHUB_SERVICE_USERS_SECRET_KEYS

GITHUB_SERVICE_USER_CONFIG_1:
  NAME: SVCGDPKIWICICD01
  EMAIL: SVCGDPKIWICICD01@sainsburys.co.uk

GITHUB_SERVICE_USER_CONFIG_2:
  NAME: gdp-kiwi-service-user-02
  EMAIL: gdp_kiwi@sainsburys.co.uk
